/**
 * @fileoverview Commit parsing and organization utilities for changelog generation.
 * 
 * This module provides comprehensive tools for parsing conventional commits,
 * filtering out automated commits, and organizing commit data into structured
 * formats suitable for changelog generation. It supports the full conventional
 * commits specification with enhanced formatting for GitHub integration.
 * 
 * @author Nyron CLI
 * @version 1.0.0
 * @since 1.0.0
 */

import type { CommitDiff } from "../github/types"
import type { ParsedCommit, ParsedCommits } from "./types"

const PullRequestRE = /\([ a-z]*(#\d+)\s*\)/gm;
const IssueRE = /(#\d+)/gm;

/**
 * Filters out meta commits (version bumps, changelog updates) from a list of commits.
 * 
 * Meta commits are typically generated by automated versioning tools and don't represent
 * actual user-facing changes. This function identifies and removes these commits to ensure
 * clean changelog generation that focuses on meaningful changes.
 * 
 * @param commits - Array of commit objects to filter
 * @returns Array of commits with meta commits removed, preserving only user-relevant changes
 * 
 * @example
 * ```typescript
 * const filteredCommits = filterMetaCommits([
 *   { message: "feat: add new feature", ... },
 *   { message: "chore: bump version to 1.2.0", ... },
 *   { message: "fix: resolve bug", ... }
 * ]);
 * // Returns only feat and fix commits, excluding the version bump
 * ```
 */
export function filterMetaCommits(commits: CommitDiff[]): CommitDiff[] {
  return commits.filter(commit => {
    const msg = commit.message.toLowerCase()
    return !(
      msg.includes('bump') && msg.includes('version') ||
      msg.includes('update changelog') ||
      msg.startsWith('chore: bump') ||
      msg.startsWith('chore: update changelog')
    )
  })
}


/**
 * Parses an array of commits into structured groups based on conventional commit format.
 * 
 * This function analyzes commit messages following the conventional commits specification
 * (https://www.conventionalcommits.org/) and organizes them into a hierarchical structure
 * by type and scope. Commits that don't match the conventional format are grouped under "other".
 * 
 * @param commits - Array of commit objects to parse
 * @returns Parsed commits organized by type and scope in the format:
 *          `{ "Features": { "scope1": [...], "general": [...] }, ... }`
 * 
 * @example
 * ```typescript
 * const parsed = parseCommits([
 *   { message: "feat(api): add authentication", ... },
 *   { message: "fix: resolve memory leak", ... },
 *   { message: "chore: update dependencies", ... }
 * ]);
 * // Returns:
 * // {
 * //   "Features": { "api": [{ type: "Features", scope: "api", message: "add authentication", ... }] },
 * //   "Bug Fixes": { "general": [{ type: "Bug Fixes", scope: "general", message: "resolve memory leak", ... }] },
 * //   "Chores": { "general": [{ type: "Chores", scope: "general", message: "update dependencies", ... }] }
 * // }
 * ```
 */
export function parseCommits(commits: CommitDiff[]): ParsedCommits {
  if (commits.length === 0) {
    throw new Error('Cannot parse commits: commits array is empty')
  }

  const groups: ParsedCommits = {}

  for (const commit of commits) {
    const raw = commit.message.trim()

    // Extract PR and issue numbers
    const prMatch = raw.match(PullRequestRE)
    const pullRequestNumber = prMatch ? parseInt(prMatch[0].match(/#(\d+)/)?.[1] || '0') : undefined
    const pullRequestUrl = pullRequestNumber ? `https://github.com/${commit.repo}/pull/${pullRequestNumber}` : undefined

    const issueMatch = raw.match(IssueRE)
    const issueNumber = issueMatch && !prMatch ? parseInt(issueMatch[0].replace('#', '')) : undefined
    const issueUrl = issueNumber ? `https://github.com/${commit.repo}/issues/${issueNumber}` : undefined

    // Match conventional commits: type(scope?): message
    const match = raw.match(/^(\w+)(?:\(([^)]+)\))?:\s*(.+)$/)
    if (!match) {
      // fallback bucket
      groups["other"] ??= { ["general"]: [] }
      if (!groups["other"]["general"]) groups["other"]["general"] = []
      groups["other"]["general"].push({ 
        type: "other", 
        message: raw, 
        raw, 
        author: commit.author, 
        hash: commit.hash, 
        repo: commit.repo,
        githubUser: commit.githubUser,
        avatar: commit.avatar,
        url: commit.url,
        pullRequestNumber,
        pullRequestUrl,
        issueNumber,
        issueUrl,
        affectedFolders: commit.affectedFolders
      })
      continue
    }

    const [, type, scope, message] = match
    const normalizedType = normalizeType(type as string)

    // ensure structure
    if (!groups[normalizedType]) groups[normalizedType] = {}
    const scopeKey = scope ?? "general"
    if (!groups[normalizedType][scopeKey]) groups[normalizedType][scopeKey] = []

    groups[normalizedType][scopeKey].push({ 
      type: normalizedType, 
      scope: scopeKey as string, 
      message: message!, 
      raw, 
      author: commit.author, 
      hash: commit.hash, 
      repo: commit.repo,
      githubUser: commit.githubUser,
      avatar: commit.avatar,
      url: commit.url,
      pullRequestNumber,
      pullRequestUrl,
      issueNumber,
      issueUrl,
      affectedFolders: commit.affectedFolders
    })
  }
  return groups
}

/**
 * Normalizes commit types into canonical, broad changelog groups.
 * 
 * This function maps a wide range of conventional (and de facto) commit types 
 * to organized, human-readable categories, making it easy to group commits 
 * for changelog or release note generation.
 * 
 * Category groupings:
 * - Features: All forms of feature additions and enhancements.
 * - Bug Fixes: All problem-solving, patch, or repair work.
 * - Documentation: Docs or meta-content changes.
 * - Refactoring: Structure or code cleanups not affecting behavior.
 * - Performance: Speed or efficiency improvements.
 * - Chores: Tooling, infra, build, workflow, or dependency updates.
 * - Tests: Test additions or improvements.
 * - Styling: Non-functional style/formatting changes.
 * - CI/CD: Pipeline and deployment improvements.
 * - Reverts, Merges, Deprecated: Special or transitional categories.
 * - Other: Unclassified/unknown types.
 * 
 * @param type - The raw commit type from the commit message.
 * @returns The broad, normalized group for changelog organization.
 * 
 * @example
 * normalizeType("feat")        // "Features"
 * normalizeType("hotfix")      // "Bug Fixes"
 * normalizeType("ci")          // "CI/CD"
 * normalizeType("wip")         // "Chores"
 * normalizeType("build")       // "Chores"
 * normalizeType("performance") // "Performance"
 * normalizeType("foo")         // "Other"
 */
function normalizeType(type: string): string {
  // Standardize case
  const raw = type.trim().toLowerCase();
  // Map of commit type synonyms -> category
  const typeMap: Record<string, string> = {
    // Features
    "feat": "Features",
    "feature": "Features",
    "enhancement": "Features",
    // Bug Fixes
    "fix": "Bug Fixes",
    "hotfix": "Bug Fixes",
    "bugfix": "Bug Fixes",
    "bug": "Bug Fixes",
    "patch": "Bug Fixes",
    // Documentation
    "docs": "Documentation",
    "doc": "Documentation",
    "documentation": "Documentation",
    // Refactors
    "refactor": "Refactoring",
    "refactoring": "Refactoring",
    "cleanup": "Refactoring",
    // Performance
    "perf": "Performance",
    "performance": "Performance",
    // Chores & Maintenance
    "chore": "Chores",
    "maintain": "Chores",
    "maintenance": "Chores",
    "deps": "Chores",
    "dependency": "Chores",
    "dependencies": "Chores",
    "build": "Chores",
    "bump": "Chores",
    "init": "Chores",
    "wip": "Chores",
    "infra": "Chores",
    "infrastructure": "Chores",
    "tool": "Chores",
    "tools": "Chores",
    "config": "Chores",
    "meta": "Chores",
    // CI/CD
    "ci": "CI/CD",
    "cd": "CI/CD",
    "pipeline": "CI/CD",
    "deploy": "CI/CD",
    // Tests
    "test": "Tests",
    "tests": "Tests",
    "testing": "Tests",
    // Styling
    "style": "Styling",
    "format": "Styling",
    "lint": "Styling",
    "prettify": "Styling",
    // Special cases
    "revert": "Reverts",
    "merge": "Merges",
    "deprecated": "Deprecated",
    // Add your own mappings as needed
  };
  return typeMap[raw] || "Other";
}

/**
 * Represents commits organized into changelog-friendly categories.
 * 
 * Each array contains formatted commit strings ready for inclusion in changelog
 * generation, with proper markdown formatting, author attribution, and commit links.
 */
export interface OrganizedCommits {
  /** Array of formatted feature commit strings */
  features: string[]
  /** Array of formatted bug fix commit strings */
  fixes: string[]
  /** Array of formatted chore/other commit strings */
  chores: string[]
}

/**
 * Organizes parsed commits into changelog-friendly categories with rich formatting.
 * 
 * This function transforms the structured commit data into formatted strings suitable
 * for changelog generation. Each commit is formatted with scope labels (when applicable),
 * author attribution with GitHub links, commit hash links, pull request references,
 * issue references, and affected folders for comprehensive context.
 * 
 * @param parsedCommits - The result from parseCommits() containing structured commit data
 * @returns An object containing three arrays of formatted commit strings:
 *          - `features`: New features and enhancements
 *          - `fixes`: Bug fixes and corrections  
 *          - `chores`: Chores, refactors, docs, tests, and other changes
 * 
 * @example
 * ```typescript
 * const parsed = parseCommits(commits);
 * const organized = organizeForChangelog(parsed);
 * // Returns:
 * // {
 * //   features: ["**api**: add authentication ([@user](https://github.com/user)) [[abc1234](https://github.com/repo/commit/abc1234...)] [#123](pr-url) [📁 packages/auth]"],
 * //   fixes: ["resolve memory leak ([@user](https://github.com/user)) [[def5678](https://github.com/repo/commit/def5678...)] [#456](issue-url)"],
 * //   chores: ["update dependencies ([@user](https://github.com/user)) [[ghi9012](https://github.com/repo/commit/ghi9012...)] [📁 packages/cli, apps/docs]"]
 * // }
 * ```
 */
export function organizCommitsForChangelog(parsedCommits: ParsedCommits): OrganizedCommits {
  const features: string[] = []
  const fixes: string[] = []
  const chores: string[] = []
  
  /**
   * Helper function to format a single commit with all metadata
   */
  const formatCommit = (commit: ParsedCommit): string => {
    const scopeLabel = commit.scope && commit.scope !== "general" ? `**${commit.scope}**: ` : ""
    const authorLink = commit.githubUser 
      ? `[@${commit.githubUser}](https://github.com/${commit.githubUser})`
      : commit.author
    const commitLink = commit.url || `https://github.com/${commit.repo}/commit/${commit.hash}`
    const shortHash = commit.hash.substring(0, 7)
    
    // Build the base message
    let formatted = `${scopeLabel}${commit.message} (${authorLink}) [[${shortHash}](${commitLink})]`
    
    // Add PR reference if available
    if (commit.pullRequestNumber && commit.pullRequestUrl) {
      formatted += ` [#${commit.pullRequestNumber}](${commit.pullRequestUrl})`
    }
    
    // Add issue reference if available (and not the same as PR)
    if (commit.issueNumber && commit.issueUrl && commit.issueNumber !== commit.pullRequestNumber) {
      formatted += ` [#${commit.issueNumber}](${commit.issueUrl})`
    }
    
    // Add affected folders if available
    if (commit.affectedFolders && commit.affectedFolders.length > 0) {
      const folders = commit.affectedFolders.join(', ')
      formatted += ` [📁 ${folders}]`
    }
    
    return formatted
  }
  
  // Process Features
  if (parsedCommits["Features"]) {
    for (const commits of Object.values(parsedCommits["Features"])) {
      for (const commit of commits) {
        features.push(formatCommit(commit))
      }
    }
  }
  
  // Process Bug Fixes
  if (parsedCommits["Bug Fixes"]) {
    for (const commits of Object.values(parsedCommits["Bug Fixes"])) {
      for (const commit of commits) {
        fixes.push(formatCommit(commit))
      }
    }
  }
  
  // Process Chores and other types
  const choreTypes = ["Chores", "Refactoring", "Performance", "Documentation", "Tests", "Styling", "CI/CD", "Reverts", "Merges", "Deprecated", "Other", "other"]
  for (const type of choreTypes) {
    if (parsedCommits[type]) {
      for (const commits of Object.values(parsedCommits[type])) {
        for (const commit of commits) {
          chores.push(formatCommit(commit))
        }
      }
    }
  }
  
  return { features, fixes, chores }
}
